# .bashrc

function parse_git_branch {
  branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
  if [[ $branch ]]; then
    echo -e " \033[1;31m($branch)\033[0m"
  fi
}

PS1='\[\033[1;33m\]\w\[\033[0m\]$(parse_git_branch)${CONDA_DEFAULT_ENV:+ \[\033[1;34m\]($CONDA_DEFAULT_ENV)\[\033[0m\]}\n\$ '

